// ─────────────────────────────────────────────────────────────────────────────
// APK release integrity pins.
//
// Every SideQuest release attaches a signed APK to the GitHub release. To stop a
// compromised-or-tampered release asset from ever being installed, the app
// verifies the downloaded file's SHA-256 against the value pinned here for the
// target version BEFORE handing it to the Android installer.
//
// This file is GENERATED by scripts/release.sh (it computes the APK's SHA-256 and
// writes the entry for the new version). Do not edit by hand — re-run the release
// script, which regenerates it. If a version has no entry, the updater skips the
// check and warns (so a manual upload still installs, just without verification).
// ─────────────────────────────────────────────────────────────────────────────

export interface ApkHashEntry {
  /** Lowercase hex SHA-256 of the release APK. */
  sha256: string
  /** When the pin was generated (ISO date) — for audit only. */
  generatedAt: string
}

/** Map of app version ("1.0.24") → expected APK hash. */
export const APK_HASHES: Record<string, ApkHashEntry> = {
  '1.0.24': {
    sha256: 'REPLACE_AT_RELEASE_TIME',
    generatedAt: '2026-08-26',
  },
}

/** Returns the pinned hash for a version, or null when unpinned. */
export function expectedApkHash(version: string): ApkHashEntry | null {
  return APK_HASHES[version] ?? null
}
