// ─────────────────────────────────────────────────────────────────────────────
// APK release integrity pins.
//
// Every SideQuest release attaches a signed APK to the GitHub release. To stop a
// compromised-or-tampered release asset from ever being installed, the app
// verifies the downloaded file's SHA-256 against the value pinned here for the
// target version BEFORE handing it to the Android installer.
//
// This file is GENERATED by scripts/release.sh (it computes the APK's SHA-256 and
// writes the entry for the new version). Do not edit by hand — re-run the release
// script, which regenerates it. If a version has no entry, the updater skips the
// check and warns (so a manual upload still installs, just without verification).
// ─────────────────────────────────────────────────────────────────────────────

export const APK_HASHES: Record<string, { sha256: string; generatedAt: string }> = {
  '1.0.24': {
    sha256: 'REPLACE_WITH_REAL_SHA256_BEFORE_RELEASE',
    generatedAt: '2026-08-26',
  },
  '1.0.25': {
    sha256: 'abebb809a91ccb0fc2897396f0da70806d2c0ec61bf0d99bfc5f2474d2d42044',
    generatedAt: '2026-08-27',
  },
}

export interface ApkHashEntry {
  /** Lowercase hex SHA-256 of the release APK. */
  sha256: string
  /** When the pin was generated (ISO date) — for audit only. */
  generatedAt: string
}

/** Returns the pinned hash for a version, or null when unpinned. */
export function expectedApkHash(version: string): ApkHashEntry | null {
  return APK_HASHES[version] ?? null
}
