// ─────────────────────────────────────────────────────────────────────────────
// Live events sync — the app side of the "auto search" pipeline.
//
// Events shown in the feed come from two sources, fetched at launch and on
// pull-to-refresh, then merged:
//
//   1. SNAPSHOT — public/events-remote.json on GitHub. Regenerated by hand with
//      scripts/fetch-events.mjs (there is no cron anymore). Always works, no
//      key needed, cached 12h per device.
//   2. LIVE — the Ticketmaster Discovery API, queried straight from the
//      browser. Ticketmaster enables CORS on this API specifically so client
//      apps can use it, so no proxy is needed. Active only when
//      VITE_TICKETMASTER_API_KEY is set (free key: developer.ticketmaster.com
//      → "Create an app"). This is what keeps the feed fresh between snapshot
//      refreshes, so events never go stale waiting on a regen. Cached 1h.
//
// Live rows win on a title|city tie. Both sources are filtered to upcoming
// events only (see isUpcomingEvent) and deduped against each other AND against
// the bundled hand-written quests, so a live festival never doubles a curated
// one.
//
// Offline-first: every fetch never throws — on any failure the previous cached
// events (or an empty list) are returned, and the bundled quests always remain
// as the fallback floor.
// ─────────────────────────────────────────────────────────────────────────────
import { ALL_QUESTS, registerCustomQuests, type Quest } from '../data/quests'
import { isUpcomingEvent } from './game'

// The snapshot feed (see header above). Override in .env with VITE_EVENTS_URL
// to point at a fork or a local dev copy.
const EVENTS_URL =
  (import.meta.env.VITE_EVENTS_URL as string | undefined) ??
  'https://raw.githubusercontent.com/JacyFleisie/sidequest/main/public/events-remote.json'

// The live source (see header above). When unset, the snapshot alone is used.
const TICKETMASTER_URL = 'https://app.ticketmaster.com/discovery/v2/events.json'
const TICKETMASTER_KEY = import.meta.env.VITE_TICKETMASTER_API_KEY as string | undefined

const SNAPSHOT_CACHE_KEY = 'sidequest:remote-events-v1'
const LIVE_CACHE_KEY = 'sidequest:live-events-v1'
const SNAPSHOT_TTL_MS = 12 * 60 * 60 * 1000 // snapshot is static; a 12h cache is fine
const LIVE_TTL_MS = 60 * 60 * 1000 // live events: keep it fresh-ish without hammering the API
const MAX_EVENTS = 30

interface RemoteEventRow {
  id: string
  title: string
  emoji?: string
  category?: string
  city: string
  province: string
  provinceName?: string
  region?: string
  lat: number
  lng: number
  durationMin?: number
  cost?: number
  players?: [number, number]
  difficulty?: 1 | 2 | 3 | 4 | 5
  vibe?: string[]
  description: string
  completionLine?: string
  xp?: number
  when?: string
  startsAt?: string
  ticketInfo?: { required?: boolean; price?: string; where?: { label: string; url?: string }[]; url?: string }
  tags?: string[]
}

/** A single event as returned by the Ticketmaster Discovery API. */
interface TicketmasterEvent {
  name?: string
  url?: string
  info?: string
  pleaseNote?: string
  dates?: { start?: { local?: string; dateTime?: string } }
  priceRanges?: { min?: number }[]
  _embedded?: { venues?: { name?: string; city?: { name?: string } }[] }
}

const PROVINCE_NAMES: Record<string, string> = {
  GP: 'Gauteng', WC: 'Western Cape', KZN: 'KwaZulu-Natal', EC: 'Eastern Cape',
  FS: 'Free State', LP: 'Limpopo', MP: 'Mpumalanga', NW: 'North West', NC: 'Northern Cape',
}

// ── SA city atlas (keep in sync with scripts/fetch-events.mjs) ───────────────
// The only cities we are confident pinning events to. An event we cannot place
// accurately is dropped — a wrong pin is worse than no pin.
const CITIES: Record<string, { province: string; lat: number; lng: number }> = {
  johannesburg: { province: 'GP', lat: -26.2041, lng: 28.0473 },
  sandton: { province: 'GP', lat: -26.1073, lng: 28.0556 },
  soweto: { province: 'GP', lat: -26.2404, lng: 27.8988 },
  braamfontein: { province: 'GP', lat: -26.1930, lng: 28.0330 },
  midrand: { province: 'GP', lat: -25.9915, lng: 28.0872 },
  randburg: { province: 'GP', lat: -26.1000, lng: 28.0000 },
  centurion: { province: 'GP', lat: -25.8589, lng: 28.1900 },
  'kempton park': { province: 'GP', lat: -26.0983, lng: 28.2289 },
  benoni: { province: 'GP', lat: -26.1884, lng: 28.3209 },
  pretoria: { province: 'GP', lat: -25.7449, lng: 28.1876 },
  'cape town': { province: 'WC', lat: -33.9249, lng: 18.4241 },
  stellenbosch: { province: 'WC', lat: -33.9347, lng: 18.8619 },
  franschhoek: { province: 'WC', lat: -33.9195, lng: 19.1187 },
  paarl: { province: 'WC', lat: -33.7286, lng: 18.9638 },
  worcester: { province: 'WC', lat: -33.6465, lng: 19.4485 },
  hermanus: { province: 'WC', lat: -34.4075, lng: 19.2437 },
  oudtshoorn: { province: 'WC', lat: -33.5892, lng: 22.2020 },
  knysna: { province: 'WC', lat: -34.0361, lng: 23.0471 },
  george: { province: 'WC', lat: -33.9610, lng: 22.4570 },
  'mossel bay': { province: 'WC', lat: -34.1833, lng: 22.1281 },
  durban: { province: 'KZN', lat: -29.8587, lng: 31.0218 },
  umhlanga: { province: 'KZN', lat: -29.7251, lng: 31.0716 },
  pietermaritzburg: { province: 'KZN', lat: -29.6006, lng: 30.3794 },
  'richards bay': { province: 'KZN', lat: -28.7805, lng: 32.0386 },
  margate: { province: 'KZN', lat: -30.8614, lng: 30.3766 },
  gqeberha: { province: 'EC', lat: -33.9608, lng: 25.6022 },
  'port elizabeth': { province: 'EC', lat: -33.9608, lng: 25.6022 },
  'east london': { province: 'EC', lat: -33.0153, lng: 27.9116 },
  'jeffreys bay': { province: 'EC', lat: -34.0507, lng: 24.9215 },
  bloemfontein: { province: 'FS', lat: -29.1175, lng: 26.2166 },
  welkom: { province: 'FS', lat: -27.9774, lng: 26.7351 },
  polokwane: { province: 'LP', lat: -23.9040, lng: 29.4680 },
  tzaneen: { province: 'LP', lat: -23.8290, lng: 30.1630 },
  mbombela: { province: 'MP', lat: -25.4833, lng: 30.9833 },
  nelspruit: { province: 'MP', lat: -25.4833, lng: 30.9833 },
  emalahleni: { province: 'MP', lat: -25.8750, lng: 29.2160 },
  rustenburg: { province: 'NW', lat: -25.6672, lng: 27.2421 },
  potchefstroom: { province: 'NW', lat: -26.7156, lng: 27.0977 },
  mahikeng: { province: 'NW', lat: -25.8527, lng: 25.6410 },
  kimberley: { province: 'NC', lat: -28.7282, lng: 24.7499 },
  upington: { province: 'NC', lat: -28.4508, lng: 21.2560 },
}

/** Venue-name hints that pin an event to a city before the fuzzy name match. */
const VENUE_HINTS: [RegExp, string][] = [
  [/time ?out market|grand ?arena|grandwest|cticc/i, 'Cape Town'],
  [/sunbet|time ?square|sun arena/i, 'Pretoria'],
  [/fnb stadium|ellis park|market theatre|goldrush dome|gold rush dome|the forum/i, 'Johannesburg'],
  [/the villa/i, 'Durban'],
  [/killarney/i, 'Cape Town'],
  [/kyalami/i, 'Midrand'],
  [/sun city/i, 'Rustenburg'],
  [/dhl stadium/i, 'Cape Town'],
]

const placeCity = (text: string | null | undefined): string | null => {
  if (!text) return null
  for (const [re, city] of VENUE_HINTS) if (re.test(text)) return city
  const lower = text.toLowerCase()
  for (const name of Object.keys(CITIES)) if (lower.includes(name)) return name
  return null
}

const cityInfo = (city: string): { city: string; province: string; lat: number; lng: number } | null => {
  const name = city.toLowerCase()
  const c = CITIES[name] ?? CITIES[Object.keys(CITIES).find((k) => name.includes(k)) ?? ''] ?? null
  if (!c) return null
  return { city: name, ...c }
}

const slug = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50)
const whenLabel = (d: Date): string =>
  d.toLocaleDateString('en-ZA', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })
const fmt = new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 })

// ── Transforms ───────────────────────────────────────────────────────────────

/** Shapes a snapshot feed row into a playable Quest. Unknown fields fall back to safe defaults. */
const rowToQuest = (r: RemoteEventRow): Quest => ({
  id: r.id,
  title: r.title,
  emoji: r.emoji ?? '🎟️',
  category: (r.category as Quest['category']) ?? 'event',
  province: (r.province as Quest['province']) ?? 'GP',
  provinceName: r.provinceName ?? PROVINCE_NAMES[r.province] ?? 'South Africa',
  city: r.city ?? 'South Africa',
  region: r.region ?? '',
  lat: r.lat,
  lng: r.lng,
  durationMin: r.durationMin ?? 150,
  cost: r.cost ?? 0,
  players: r.players ?? [1, 8],
  difficulty: r.difficulty ?? 1,
  vibe: (r.vibe as Quest['vibe']) ?? ['entertainment'],
  description: r.description,
  completionLine: r.completionLine ?? 'You were there. Legend.',
  xp: r.xp ?? 300,
  when: r.when,
  startsAt: r.startsAt,
  ticketInfo: r.ticketInfo,
  tags: r.tags ?? ['live'],
})

/**
 * Shapes a raw Ticketmaster event into a playable Quest.
 * Returns null when the event is in the past or can't be pinned to a known
 * SA city — we never show an event we can't place accurately.
 */
export const liveEventToQuest = (ev: TicketmasterEvent, now: Date): Quest | null => {
  const venue = ev._embedded?.venues?.[0]
  const startRaw = ev.dates?.start?.local ?? ev.dates?.start?.dateTime
  const start = startRaw ? new Date(startRaw) : null
  if (!start || Number.isNaN(start.getTime())) return null
  if (start.getTime() < now.getTime() - 86_400_000) return null // drop past events

  const info = cityInfo(venue?.city?.name ?? placeCity(venue?.name) ?? '')
  if (!info) return null // never pin an event we can't place accurately

  const minPrice = ev.priceRanges?.[0]?.min
  const priceLabel = typeof minPrice === 'number' ? `from ${fmt.format(Math.round(minPrice))}` : 'prices vary'
  return {
    // The `remote-` prefix is the app-wide contract for "auto-discovered live
    // event" (map pins, the Live feed filter) — keep it for live rows too.
    id: `remote-ticketmaster-${slug(ev.name ?? '')}-${start.getFullYear()}${String(start.getMonth() + 1).padStart(2, '0')}${String(start.getDate()).padStart(2, '0')}`,
    title: ev.name ?? 'Untitled event',
    emoji: '🎟️',
    category: 'event',
    city: info.city,
    province: info.province as Quest['province'],
    provinceName: PROVINCE_NAMES[info.province],
    region: '',
    lat: info.lat,
    lng: info.lng,
    durationMin: 150,
    cost: 0,
    players: [1, 8],
    difficulty: 1,
    vibe: ['entertainment'],
    description:
      ev.info?.slice(0, 240) ||
      'A live ticketed event in South Africa — grab your tickets on Ticketmaster.',
    completionLine: 'You were there. Legend.',
    xp: 300,
    when: whenLabel(start),
    startsAt: start.toISOString(),
    ticketInfo: {
      required: true,
      price: priceLabel,
      where: [{ label: 'Online at Ticketmaster', url: ev.url }],
    },
    tags: ['ticketmaster', 'live', info.city.replace(/\s+/g, '-')],
  }
}

/**
 * Merges the snapshot and live feeds into one deduped, upcoming-only list.
 * Live rows win on a title|city tie. Bundled hand-written quests are never
 * duplicated. Sorted by start date, capped at MAX_EVENTS.
 */
export const mergeEventSources = (snapshot: Quest[], live: Quest[]): Quest[] => {
  const bundledTitles = new Set(ALL_QUESTS.map((q) => q.title.toLowerCase()))
  const seen = new Set<string>()
  const out: Quest[] = []
  for (const q of [...live, ...snapshot]) {
    if (bundledTitles.has(q.title.toLowerCase())) continue
    const key = `${q.title.toLowerCase()}|${q.city.toLowerCase()}`
    if (seen.has(key)) continue
    seen.add(key)
    out.push(q)
  }
  return out
    .filter(isUpcomingEvent)
    .sort((a, b) => (a.startsAt ?? '').localeCompare(b.startsAt ?? ''))
    .slice(0, MAX_EVENTS)
}

// ── Caching ──────────────────────────────────────────────────────────────────

const readCache = (key: string, ttlMs: number): Quest[] | null => {
  try {
    const raw = localStorage.getItem(key)
    if (!raw) return null
    const { at, events } = JSON.parse(raw) as { at: number; events: Quest[] }
    if (Date.now() - at > ttlMs) return null
    return events
  } catch {
    return null
  }
}

const writeCache = (key: string, events: Quest[]) => {
  try {
    localStorage.setItem(key, JSON.stringify({ at: Date.now(), events }))
  } catch {
    // storage full/blocked — the feed just fetches again next launch
  }
}

// ── Fetching ─────────────────────────────────────────────────────────────────

/** Fetches the static snapshot feed (cached SNAPSHOT_TTL_MS). Never throws. */
async function fetchSnapshot(force = false): Promise<Quest[]> {
  const cached = readCache(SNAPSHOT_CACHE_KEY, SNAPSHOT_TTL_MS)
  if (cached && !force) return cached
  try {
    const res = await fetch(EVENTS_URL, { signal: AbortSignal.timeout(10_000) })
    if (!res.ok) return cached ?? []
    const data = (await res.json()) as { events?: RemoteEventRow[] }
    const events = (data.events ?? []).map(rowToQuest)
    if (events.length > 0) writeCache(SNAPSHOT_CACHE_KEY, events)
    return events.length > 0 ? events : (cached ?? [])
  } catch {
    return cached ?? []
  }
}

/**
 * Queries the Ticketmaster Discovery API for upcoming ZA events (cached
 * LIVE_TTL_MS). No-ops when VITE_TICKETMASTER_API_KEY is unset. Never throws —
 * a failure falls back to the cached live list, then to nothing.
 */
async function fetchLiveEvents(force = false): Promise<Quest[]> {
  if (!TICKETMASTER_KEY) return []
  const cached = readCache(LIVE_CACHE_KEY, LIVE_TTL_MS)
  if (cached && !force) return cached
  try {
    const params = new URLSearchParams({
      apikey: TICKETMASTER_KEY,
      countryCode: 'ZA',
      sort: 'date,asc',
      size: '100',
      includeTBA: 'no',
      includeTBD: 'no',
    })
    const res = await fetch(`${TICKETMASTER_URL}?${params}`, { signal: AbortSignal.timeout(10_000) })
    if (!res.ok) return cached ?? []
    const data = (await res.json()) as { _embedded?: { events?: TicketmasterEvent[] } }
    const events = (data._embedded?.events ?? [])
      .map((ev) => liveEventToQuest(ev, new Date()))
      .filter((q): q is Quest => q !== null)
    if (events.length > 0) writeCache(LIVE_CACHE_KEY, events)
    return events.length > 0 ? events : (cached ?? [])
  } catch {
    return cached ?? []
  }
}

/** Fetches the merged snapshot + live events feed. Never throws — returns [] offline. */
export async function fetchRemoteEvents(force = false): Promise<Quest[]> {
  const [snapshot, live] = await Promise.all([fetchSnapshot(force), fetchLiveEvents(force)])
  return mergeEventSources(snapshot, live)
}

/** Fetches + registers live events app-wide so quest sheets resolve them, then
 * tells the feed to re-render. Fire-and-forget from App boot and feed refresh. */
export async function syncRemoteEvents(force = false): Promise<Quest[]> {
  const events = await fetchRemoteEvents(force)
  if (events.length > 0) {
    registerCustomQuests(events)
    window.dispatchEvent(new CustomEvent('sidequest:remote-events'))
  }
  return events
}
